input:
  input_video_path: data/Videos
  frame_extraction_dir: data/scene_changing_frames
  scene_changing_threshold:
    default: 0.2
    video1: 0.05
    video6: 0.1
    video9: 0.1
    video10: 0.05
query:
  input_video_path: data/Queries
  frame_extraction_dir: data/scene_changing_query_frames
  scene_changing_threshold:
    default: 0.01