input:
  input_video_path: data/Videos
  frame_extraction_dir: data/extracted_input_frames
query:
  input_video_path: data/Queries
  frame_extraction_dir: data/extracted_query_frames
towhee_params:
  model: resnet50