visual:
  limit: 10
  output_fields:
    - video_id
    - frame_id
  anns_field: visual_embedding
  param:
    params:
      nprobe: 10
    metric_type: L2
audio:
  limit: 10
  output_fields:
    - video_id
    - time
  anns_field: audio_embedding
  param:
    params:
      nprobe: 10
    metric_type: IP