video1:
  total_length: 954
video2:
  total_length: 788
video3:
  total_length: 682
video4:
  total_length: 1002
video5:
  total_length: 622
video6:
  total_length: 846
video7:
  total_length: 676
video8:
  total_length: 790
video9:
  total_length: 788
video10:
  total_length: 838
video11:
  total_length: 577
video12:
  total_length: 581
video13:
  total_length: 821
video14:
  total_length: 655
video15:
  total_length: 657
video16:
  total_length: 798
video17:
  total_length: 536
video18:
  total_length: 821
video19:
  total_length: 483
video20:
  total_length: 568